In [1]:
import numpy as np
from modules.util_classes import Coor
from modules.util_functions import hashFunction

In [2]:
arr = np.arange(12).reshape(4, 3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
arr[[(0,0), (0, 1), (0,2)]] = -1
arr

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [11]:
b

array([[0, 1],
       [3, 4]])

In [8]:
hashFunction(a)

'dcd8a25b4216059cededec353d4093075c5d75d3'

In [6]:
a = np.arange(10)

np.random.shuffle(a)

a

array([9, 7, 8, 5, 0, 4, 6, 2, 3, 1])

In [7]:
arr.shape

(4, 3)

In [3]:
a = [1, 2, 3, 4]


a[1:]

[2, 3, 4]

In [6]:
(1, 2) == (2, 2)

False

In [5]:
a = ''

if not a:
    print('ok')

ok


In [1]:
i = 0

i += True

i

1

In [1]:
import numpy as np

In [10]:
np.random.randint(4)

2

In [11]:
np.arange(4)

array([0, 1, 2, 3])