In [1]:
import numpy as np
from modules.util_classes import Coor
from modules.util_functions import hashFunction

In [2]:
arr = np.arange(12).reshape(4, 3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
np.sum(arr % 2 == 0)

6

In [11]:
b

array([[0, 1],
       [3, 4]])

In [8]:
hashFunction(a)

'dcd8a25b4216059cededec353d4093075c5d75d3'

In [6]:
a = np.arange(10)

np.random.shuffle(a)

a

array([9, 7, 8, 5, 0, 4, 6, 2, 3, 1])

In [7]:
arr.shape

(4, 3)